name: Integration release auto-approve

# Controls when the action will run.
on:
  pull_request:
    branches: [production]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'integration-release-to-production'
    steps:
      - name: Approve a PR
        run: gh pr review --approve "$PR_NUMBER"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
